version: '3' 
services:
    opendaylight:
        build:
            context: .
            dockerfile: ./opendaylight/Dockerfile 
        container_name: opendaylight
        tty: true
        ports:
            - 8181:8181
        networks:
            project3a-network:
                ipv4_address: 172.20.0.2
        container_name: open_day_light

    mininet:
        build:
            context: .
            dockerfile: ./mininet/Dockerfile
        environment:
            - DISPLAY
        #volumes:
        #    - /tmp/.X11-unix:/tmp/.X11-unix
        #    - /lib/modules:/lib/modules
        tty: true
        #network_mode: "bridge"
        privileged: true
        #cap_add:
        #    - SYS_ADMIN
        ##security_opt:
        #   - seccomp:unconfined
        #volumes:
        #    - /sys/fs/cgroup:/sys/fs/cgroup:ro
        entrypoint: entrypoint.sh
        container_name: mininet
        ports:
            - 6633:6633
            - 6640:6640
            - 6653:6653
        networks:
            project3a-network:
                ipv4_address: 172.20.0.33
        container_name: mininet

networks:
    project3a-network:
        driver: bridge
        ##external: true
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16
